global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'slack'

receivers:
- name: 'slack'
  slack_configs:
  - channel: '#all-nyu'
    send_resolved: true
    api_url: 'https://hooks.slack.com/services/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'
